version: "3.7"

services:
    product_app:
        build: ./product_app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./product_app/:/product_app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    token_app:
        build: ./token_app
        command: python manage.py runserver 0.0.0.0:3333
        volumes:
            - ./token_app/:/token_app/
        ports:
            - 3333:3333
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

volumes:
    postgres_data:
    product_app:
    token_app:
