# Generated by Django 3.2.6 on 2021-08-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
    ]
